name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
jobs:
  build:
    uses: bmw-tech-talent-days/bmw.cloudadoption.workflows/.github/workflows/java-build.yaml@main
    with:
      ACR_REPOSITORY: "vehicle-order-service-java"
      DOCKERFILE_PATH: src/main/docker/Dockerfile.jvm
      JAVA_VERSION: '11'
      MAVEN_VERSION: "3.8.2"
    secrets:
      AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      TTD_GITHUB_TOKEN: ${{ secrets.TTD_GITHUB_TOKEN }}


