name: Deploy

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Patch deployment
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        shell: bash
        run: |
          aws eks update-kubeconfig --name ttd --alias ttd
          kubectl -n ttd-dev patch deployment vehicle-order-service-java -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"kubectl.kubernetes.io/restartedAt\": \"$(date +"%Y-%m-%dT%H:%M:%SZ")\"}}}}}"
        env:
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}